#!/usr/bin/env python

from subprocess import call, check_output
from sys import exit

def conflicted_files():
    return filter(
        None,
        check_output(
            'git --no-pager diff --name-only --diff-filter=U',
            shell=True).split('\n'))

commands = [
    'Gmerge',
    'Gdiff',
    'set noro',
    'nmap <leader>dt :ConflictMarkerOurselves<CR>',
    'nmap <leader>dm :ConflictMarkerThemselves<CR>',
    'nmap <leader>n :call NextMergeConflict()<CR>',
    'normal gg',
    'ConflictMarkerNextHunk'
    ]
arguments = ' '.join(map(lambda x: '-c "%s"' % x, commands))

while True:
    if not conflicted_files():
        break
    vim = call('vim %s .' % arguments, shell=True)
    if vim:
        exit(1)
    call('EDITOR=cat git rebase --continue', shell=True)
