#!/bin/bash

# Reorders existing sessions, then creates a new session

temp_file=/tmp/$$.tmp
n=1
tmux list-sessions | awk '{print $1}' | cut -d: -f1 | while read i; do
  if [[ $i = 'no' ]]; then
    echo $n > $temp_file
    break
  elif [[ $i != $n ]]; then
    tmux rename-session -t $i $n
  fi
  ((n++))
  echo $n > $temp_file
done

n=$(cat $temp_file)
unlink $temp_file
tmux new-session -s $n -d
