#!/usr/bin/env python2.7

import re
from subprocess import call
from sys import argv

# This supports the -G flag, which filters by regex
# https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage
optional = ' '.join(
    map(lambda x: re.sub('=', ' ', x),
        filter(lambda y: y.startswith('-'),
               argv[1:])))
positional = filter(lambda x: not x.startswith('-'), argv[1:])

pattern = "'%s'" % positional[0]
directory = '.'
if len(positional) > 1:
    directory = positional[1]

args = filter(lambda x: x, [optional, pattern, directory])
command = 'vim -n -c "setlocal shellpipe=>" -c "Ack %s"' % ' '.join(args)
call(command, shell=True)
